// Venue lookup by match_number — sourced from world-cup-2026-schedule.json
export const VENUE_BY_MATCH = {
  1:   'Estadio Azteca, Mexico City',
  2:   'Estadio Akron, Guadalajara',
  3:   'BMO Field, Toronto',
  4:   'SoFi Stadium, Los Angeles',
  5:   'Gillette Stadium, Boston',
  6:   'BC Place, Vancouver',
  7:   'MetLife Stadium, New York/New Jersey',
  8:   "Levi's Stadium, San Francisco Bay Area",
  9:   'Lincoln Financial Field, Philadelphia',
  10:  'NRG Stadium, Houston',
  11:  'AT&T Stadium, Dallas',
  12:  'Estadio BBVA, Monterrey',
  13:  'Hard Rock Stadium, Miami',
  14:  'Mercedes-Benz Stadium, Atlanta',
  15:  'SoFi Stadium, Los Angeles',
  16:  'Lumen Field, Seattle',
  17:  'MetLife Stadium, New York/New Jersey',
  18:  'Gillette Stadium, Boston',
  19:  'Arrowhead Stadium, Kansas City',
  20:  "Levi's Stadium, San Francisco Bay Area",
  21:  'BMO Field, Toronto',
  22:  'AT&T Stadium, Dallas',
  23:  'NRG Stadium, Houston',
  24:  'Estadio Azteca, Mexico City',
  25:  'Mercedes-Benz Stadium, Atlanta',
  26:  'SoFi Stadium, Los Angeles',
  27:  'BC Place, Vancouver',
  28:  'Estadio Akron, Guadalajara',
  29:  'Lincoln Financial Field, Philadelphia',
  30:  'Gillette Stadium, Boston',
  31:  "Levi's Stadium, San Francisco Bay Area",
  32:  'Lumen Field, Seattle',
  33:  'BMO Field, Toronto',
  34:  'Arrowhead Stadium, Kansas City',
  35:  'NRG Stadium, Houston',
  36:  'Estadio BBVA, Monterrey',
  37:  'Hard Rock Stadium, Miami',
  38:  'Mercedes-Benz Stadium, Atlanta',
  39:  'SoFi Stadium, Los Angeles',
  40:  'BC Place, Vancouver',
  41:  'MetLife Stadium, New York/New Jersey',
  42:  'Lincoln Financial Field, Philadelphia',
  43:  'AT&T Stadium, Dallas',
  44:  "Levi's Stadium, San Francisco Bay Area",
  45:  'Gillette Stadium, Boston',
  46:  'BMO Field, Toronto',
  47:  'NRG Stadium, Houston',
  48:  'Estadio Akron, Guadalajara',
  49:  'Hard Rock Stadium, Miami',
  50:  'Mercedes-Benz Stadium, Atlanta',
  51:  'BC Place, Vancouver',
  52:  'Lumen Field, Seattle',
  53:  'Estadio Azteca, Mexico City',
  54:  'Estadio BBVA, Monterrey',
  55:  'Lincoln Financial Field, Philadelphia',
  56:  'MetLife Stadium, New York/New Jersey',
  57:  'AT&T Stadium, Dallas',
  58:  'Arrowhead Stadium, Kansas City',
  59:  'SoFi Stadium, Los Angeles',
  60:  "Levi's Stadium, San Francisco Bay Area",
  61:  'Gillette Stadium, Boston',
  62:  'BMO Field, Toronto',
  63:  'Lumen Field, Seattle',
  64:  'BC Place, Vancouver',
  65:  'NRG Stadium, Houston',
  66:  'Estadio Akron, Guadalajara',
  67:  'MetLife Stadium, New York/New Jersey',
  68:  'Lincoln Financial Field, Philadelphia',
  69:  'Arrowhead Stadium, Kansas City',
  70:  'AT&T Stadium, Dallas',
  71:  'Hard Rock Stadium, Miami',
  72:  'Mercedes-Benz Stadium, Atlanta',
  73:  'SoFi Stadium, Los Angeles',
  74:  'Gillette Stadium, Boston',
  75:  'Estadio BBVA, Monterrey',
  76:  'NRG Stadium, Houston',
  77:  'MetLife Stadium, New York/New Jersey',
  78:  'AT&T Stadium, Dallas',
  79:  'Estadio Azteca, Mexico City',
  80:  'Mercedes-Benz Stadium, Atlanta',
  81:  "Levi's Stadium, San Francisco Bay Area",
  82:  'Lumen Field, Seattle',
  83:  'BMO Field, Toronto',
  84:  'SoFi Stadium, Los Angeles',
  85:  'BC Place, Vancouver',
  86:  'Hard Rock Stadium, Miami',
  87:  'Arrowhead Stadium, Kansas City',
  88:  'AT&T Stadium, Dallas',
  89:  'Lincoln Financial Field, Philadelphia',
  90:  'NRG Stadium, Houston',
  91:  'MetLife Stadium, New York/New Jersey',
  92:  'Estadio Azteca, Mexico City',
  93:  'AT&T Stadium, Dallas',
  94:  'Lumen Field, Seattle',
  95:  'Mercedes-Benz Stadium, Atlanta',
  96:  'BC Place, Vancouver',
  97:  'Gillette Stadium, Boston',
  98:  'SoFi Stadium, Los Angeles',
  99:  'Hard Rock Stadium, Miami',
  100: 'Arrowhead Stadium, Kansas City',
  101: 'AT&T Stadium, Dallas',
  102: 'Mercedes-Benz Stadium, Atlanta',
  103: 'Hard Rock Stadium, Miami',
  104: 'MetLife Stadium, New York/New Jersey',
};
